Update issue link to apache
apache/amoro pull request #2741
Opened 2024-04-14 08:18 UTC by xleoken

## Why are the changes needed?

Close #xxx.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2024-04-14 08:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/apache/amoro?pullRequest=2741) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/apache/amoro?pullRequest=2741) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/apache/amoro?pullRequest=2741) it.</sub>

2024-04-15 02:03 UTC, zhongqishang approved these changes
LGTM. Thanks for your contribution.

2024-04-15 02:09 UTC, zhongqishang commented on .idea/vcs.xml
> +          <option name="linkRegexp" value="https://github.com/apache/amoro/pulls/$1" />
Sorry I miss one that `/pull` should not be changed to `/pulls`.

2024-04-15 02:36 UTC, baiyangtx requested changes

2024-04-15 02:36 UTC, baiyangtx commented on .idea/vcs.xml
> +          <option name="linkRegexp" value="https://github.com/apache/amoro/pulls/$1" />
```suggestion
          <option name="linkRegexp" value="https://github.com/apache/amoro/pull/$1" />
```

2024-04-15 02:53 UTC, xleoken commented
thanks @baiyangtx @zhongqishang

2024-04-15 02:53 UTC, xleoken commented on .idea/vcs.xml
> +          <option name="linkRegexp" value="https://github.com/apache/amoro/pulls/$1" />
updated.

2024-04-15 03:33 UTC, baiyangtx approved these changes
LGTM

2024-04-15 03:33 UTC, merged